# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='Topic',
            new_name='topic',
        ),
    ]
